version: '3.9'
services:
  docx-pdf-api:
    env_file:
      - .env
    image: docx-pdf-api
    ports:
      - "${EXPOSE_PORT}:8080"
    restart: unless-stopped
    networks:
      - file-convertor-api-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
networks:
  file-convertor-api-network:
    driver: bridge
